
default: &default
    adapter: postgresql
    encoding: unicode

    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

    host: localhost

    username: zpyly

    password: 'root'

    port: 5432

development:
    <<: *default
    database: sporthub_development

test:
    <<: *default
    database: sporthub_test

production:
    <<: *default
    database: sporthub_production
    username: sporthub
    password: <%= ENV["SPORTHUB_DATABASE_PASSWORD"] %>
